"""table right_user change column object_access -> del unique

Revision ID: 2f4b03e8e063
Revises: 477a313700e1
Create Date: 2024-03-04 13:10:18.798895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4b03e8e063'
down_revision: Union[str, None] = '477a313700e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('right_user_object_access_key', 'right_user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('right_user_object_access_key', 'right_user', ['object_access'])
    # ### end Alembic commands ###
