"""table objects change column name -> del unique

Revision ID: 477a313700e1
Revises: 10ee630d9282
Create Date: 2024-03-04 13:00:47.317885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477a313700e1'
down_revision: Union[str, None] = '10ee630d9282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('objects_name_key', 'objects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('objects_name_key', 'objects', ['name'])
    # ### end Alembic commands ###
